apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-k8s-deployment
  namespace: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-k8s-app
    spec:
      containers:
      - name: sample-k8s-app
        image: simranjeetwalia/sample-app:${BUILD_ID}
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ${KUBERNETES_SECRET_NAME}
