apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: jenkins
  labels:
    name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
